### ISSUE TITLE
can't login, can't get "forgot your password"

### ISSUE THREAD

**Issue by ajft** [sachac/quantified#5]
Forgive me for contacting this way, but having registered on the site on 2014-07-05 (yes, 3yrs ago) and only briefly using it, I've now tried to log back in and the pwd I thought I'd used doesn't work.

Trying the "forgot my password" link results in no email to my account, trying the "resend email" link results in an error message that the email has already been sent, and trying to register a new account with the same email address results in the error that my email address is already in use.

**Comment by ajft** [comment]
So as usually happens, having tried the "send email" "resend email" yesterday, today when I tried it I receive the email and I've logged back in.  Appologies for taking up any time here.

**Comment by sachac** [comment]
Thanks for the update, and for trying this out! :)

On Aug 20, 2017 11:22 PM, "Adrian Tritschler" <notifications@github.com>
wrote:

So as usually happens, having tried the "send email" "resend email"
yesterday, today when I tried it I receive the email and I've logged back
in. Appologies for taking up any time here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sachac/quantified/issues/5#issuecomment-323637956>, or mute
the thread
